name: task_manager
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  freezed_annotation: ^2.4.4
  intl: ^0.19.0
  go_router: ^14.2.0
  material_symbols_icons: ^4.2801.1
  json_annotation: ^4.9.0
  google_fonts: ^6.2.1
  logging: ^1.3.0
  asuka: ^2.2.1
  sqflite: ^2.4.1
  path: ^1.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7

  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^4.0.0
  json_serializable: ^6.9.0
  mocktail: ^1.0.4
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

